/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saccomanager;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Programmer
 */
public class loan_repayment extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
Statement stm=null;
    /**
     * Creates new form loan_repayment
     */
    public loan_repayment() {
        initComponents();
    }

     private void totalpay(){
         connection connect=new connection();
         conn=connect.Connectdb();
   
    try{
        stm = conn.createStatement();
        String coun="select SUM(amount_paid)from `loan_repayment`";
        
        rs=stm.executeQuery(coun);
        if( rs.next()){
        String in=rs.getString("SUM(amount_paid)");
        float on=Integer.parseInt(in);
        amount.setText(""+on);
        }
       }
    
    catch(Exception e){
    JOptionPane.showMessageDialog(null,e.getMessage());
    }
     
     } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birthdayEvaluator1 = new com.toedter.calendar.demo.BirthdayEvaluator();
        dateUtil1 = new com.toedter.calendar.DateUtil();
        birthdayEvaluator2 = new com.toedter.calendar.demo.BirthdayEvaluator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        middlename = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        national = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maritalstatus = new javax.swing.JTextField();
        f1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        f11 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();
        s7 = new javax.swing.JLabel();
        f7 = new javax.swing.JLabel();
        s8 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        memberidentification = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        minum = new javax.swing.JTextField();
        aplon = new javax.swing.JTextField();
        inst = new javax.swing.JTextField();
        fpd = new javax.swing.JTextField();
        tint = new javax.swing.JTextField();
        tlonpay = new javax.swing.JTextField();
        risk = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        payment = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        bal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nins = new javax.swing.JTextField();
        totalpay = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCalendar2 = new org.freixas.jcalendar.JCalendar();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Confirmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        middlename.setEditable(false);
        middlename.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        middlename.setToolTipText("This is not editable");
        middlename.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        middlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                middlenameKeyTyped(evt);
            }
        });
        jPanel3.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 142, -1));

        surname.setEditable(false);
        surname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        surname.setToolTipText("This is not editable");
        surname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                surnameKeyTyped(evt);
            }
        });
        jPanel3.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 142, -1));

        firstname.setEditable(false);
        firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        firstname.setToolTipText("This is not editable");
        firstname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameKeyTyped(evt);
            }
        });
        jPanel3.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 142, -1));

        national.setEditable(false);
        national.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        national.setToolTipText("This is not editable");
        national.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        national.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nationalKeyTyped(evt);
            }
        });
        jPanel3.add(national, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 142, -1));

        contact.setEditable(false);
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setToolTipText("This is not editable");
        contact.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contactKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });
        jPanel3.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 142, -1));

        email.setEditable(false);
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setToolTipText("This is not editable");
        email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 142, -1));

        jLabel3.setText("First Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setText("Middle Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setText("National ID");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setText("Surname");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel7.setText("Marital Status");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setText("Email");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel9.setText("Contact");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        maritalstatus.setEditable(false);
        maritalstatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maritalstatus.setToolTipText("This is not editable");
        maritalstatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(maritalstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 142, -1));
        jPanel3.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 38, -1, -1));
        jPanel3.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 38, 16, -1));
        jPanel3.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 44, -1, -1));
        jPanel3.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 44, 16, -1));
        jPanel3.add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 102, -1, -1));
        jPanel3.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 102, 16, -1));
        jPanel3.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 140, -1, -1));
        jPanel3.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 158, -1, -1));
        jPanel3.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 158, 16, -1));
        jPanel3.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 216, -1, -1));
        jPanel3.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 216, 16, -1));
        jPanel3.add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 254, -1, -1));
        jPanel3.add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 254, 16, -1));
        jPanel3.add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 272, -1, -1));
        jPanel3.add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 272, 16, -1));
        jPanel3.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 140, 16, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, -1, 310));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        memberidentification.setToolTipText("Enter member identification code ");
        memberidentification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                memberidentificationMouseExited(evt);
            }
        });
        memberidentification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memberidentificationKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                memberidentificationKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                memberidentificationKeyTyped(evt);
            }
        });
        jPanel2.add(memberidentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/3.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 3, 202, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("P/NO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 14, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 301, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select---", "Normal Loan", "Special Loan", "Emergency Loan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 120, -1));

        jLabel10.setText("SELECT LOAN TO PAY");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 121, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minum.setEditable(false);
        minum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(minum, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 13, 140, -1));

        aplon.setEditable(false);
        aplon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aplon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(aplon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, -1));

        inst.setEditable(false);
        inst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inst.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(inst, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, -1));

        fpd.setEditable(false);
        fpd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fpd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(fpd, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, -1));

        tint.setEditable(false);
        tint.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tint.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(tint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, -1));

        tlonpay.setEditable(false);
        tlonpay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tlonpay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(tlonpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, -1));

        risk.setEditable(false);
        risk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        risk.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(risk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, -1));
        jPanel8.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 240, -1));

        jLabel11.setText("Approved Loan");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, -1));

        jLabel12.setText("Installments");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, -1));

        jLabel13.setText("First-Perio Deduction");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, -1));

        jLabel14.setText("Total Interest");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, -1));

        jLabel15.setText("Total Loan Payment");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));

        jLabel16.setText("Risk Fund");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));

        jLabel18.setText("Date Paid(Time Stamp)");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "COMMENT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 14))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jLabel19.setText("Amount Paid");

        payment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        payment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        payment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentKeyReleased(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Success.png"))); // NOI18N
        jButton4.setText("VALIDATE PAYMENT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel20.setText("Current Balance");

        bal.setEditable(false);
        bal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setText("Next Installment");

        nins.setEditable(false);
        nins.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nins.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        totalpay.setEditable(false);
        totalpay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalpay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        amount.setEditable(false);
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setText("Previously Paid");

        jLabel23.setText("Currently Paid");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payment))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nins))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalpay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bal)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(1056, 1056, 1056))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(nins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 540, 311));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 13, 560, 368));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/btn_update.png"))); // NOI18N
        jButton1.setText("Update Savings");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bar-code_48x48.png"))); // NOI18N
        jButton3.setText("Print Receipt");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 387, 870, -1));

        jCalendar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jCalendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 315, 440));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home.png"))); // NOI18N
        jLabel17.setToolTipText("CLOSE SAVINGS SYSTEM");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1246, 517));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void middlenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_middlenameKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='A')&&(c<='Z')||(c>='a')&&(c<='z')||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER)||(c==KeyEvent.VK_CAPS_LOCK)||(c==KeyEvent.VK_SHIFT)||(c==KeyEvent.VK_SPACE))){
            middlename.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Enter Characters Only");
            evt.consume();
        }
        else{
            middlename.setBackground(Color.LIGHT_GRAY);

        } // TODO add your handling code here:
    }//GEN-LAST:event_middlenameKeyTyped

    private void surnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameKeyTyped

        char c = evt.getKeyChar();
        if(!((c>='A')&&(c<='Z')||(c>='a')&&(c<='z')||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER)||(c==KeyEvent.VK_CAPS_LOCK)||(c==KeyEvent.VK_SHIFT)||(c==KeyEvent.VK_SPACE))){
            surname.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Enter Characters Only");
            evt.consume();
        }
        else{
            surname.setBackground(Color.LIGHT_GRAY);

        }// TODO add your handling code here:
    }//GEN-LAST:event_surnameKeyTyped

    private void firstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameKeyTyped
        char c = evt.getKeyChar();
        if(!((c>='A')&&(c<='Z')||(c>='a')&&(c<='z')||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER)||(c==KeyEvent.VK_CAPS_LOCK)||(c==KeyEvent.VK_SHIFT)||(c==KeyEvent.VK_SPACE))){
            firstname.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Enter Characters Only");
            evt.consume();
        }
        else{
            firstname.setBackground(Color.LIGHT_GRAY);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameKeyTyped

    private void nationalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nationalKeyTyped
        char c=evt.getKeyChar();
        if(!((c>='0')&&(c<='9')||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER))){
            national.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Enter Numerics Only");
            evt.consume();
        }
        else{
            national.setBackground(Color.LIGHT_GRAY);

        } // TODO add your handling code here:
    }//GEN-LAST:event_nationalKeyTyped

    private void contactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyReleased
        String telno = contact.getText();
        int length = telno.length();

        if(length>=10){
            telno = telno.substring(0, 10);
            contact.setText(telno);
            f5.setVisible(false);
            s6.setVisible(true);
        }
        if(length<10){
            contact.setBackground(Color.red);
            f5.setVisible(true);
            s6.setVisible(false);
            //JOptionPane.showMessageDialog(null, "Please enter valid telephone number");
            // contact.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_contactKeyReleased

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char c=evt.getKeyChar();
        if(!((c>='0')&&(c<='9')||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER))){
            contact.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Enter Numerics Only");
            evt.consume();
        }
        else{
            contact.setBackground(Color.LIGHT_GRAY);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_contactKeyTyped

    private void memberidentificationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberidentificationMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_memberidentificationMouseExited

    private void memberidentificationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberidentificationKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_memberidentificationKeyPressed

    private void memberidentificationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberidentificationKeyReleased
        String loannum = (memberidentification.getText());
        connection connect = new connection();
        conn = (com.mysql.jdbc.Connection) connect.Connectdb();
        try {
            //java.sql.Statement stm=conn.createStatement();
            java.sql.Statement stm = conn.createStatement();
            String sql = "SELECT * FROM registry where Member_Id='" + loannum + "'";

            rs = stm.executeQuery(sql);

            if (rs.next()) {
                String fao=rs.getString("F_Name");
                String mid=rs.getString("M_Name");
                String sur=rs.getString("S_Name");
                String num=rs.getString("Id/pass_No");
                String con=rs.getString("Contant");
                String em=rs.getString("E_Mail");
                String ms=rs.getString("Maritual_Status");

                firstname.setText(fao);
                firstname.setBackground(Color.GRAY);
                middlename.setText(mid);
                middlename.setBackground(Color.GRAY);
                surname.setText(sur);
                surname.setBackground(Color.GRAY);
                national.setText(num);
                national.setBackground(Color.GRAY);
                contact.setText(con);
                contact.setBackground(Color.GRAY);
                email.setText(em);
                email.setBackground(Color.GRAY);
                maritalstatus.setText(ms);
                maritalstatus.setBackground(Color.GRAY);

            }

            else{
                firstname.setText("");
                firstname.setBackground(Color.LIGHT_GRAY);
                middlename.setText("");
                middlename.setBackground(Color.LIGHT_GRAY);
                surname.setText("");
                surname.setBackground(Color.LIGHT_GRAY);
                national.setText("");
                national.setBackground(Color.LIGHT_GRAY);
                contact.setText("");
                contact.setBackground(Color.LIGHT_GRAY);
                email.setText("");
                email.setBackground(Color.LIGHT_GRAY);
                maritalstatus.setText("");
                maritalstatus.setBackground(Color.LIGHT_GRAY);

            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

        catch(Exception e){
            //JOptionPane.showMessageDialog(null, e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_memberidentificationKeyReleased

    private void memberidentificationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memberidentificationKeyTyped
        char c=evt.getKeyChar();
        if(!((c>='0')&&(c<='9')||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_ENTER))){
            memberidentification.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Enter Numerics Only");
            evt.consume();
        }
        else{
            memberidentification.setBackground(Color.LIGHT_GRAY);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_memberidentificationKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String member=memberidentification.getText();
        String fnam=firstname.getText();
        String midnam=middlename.getText();
        String sur=surname.getText();
        String lnation=national.getText();
        String con=contact.getText();
        String emai=email.getText();
        String marita=maritalstatus.getText();
        String minite=minum.getText();
        String aplo=aplon.getText();
        String insta=inst.getText();
        String fast=fpd.getText();
        String totinterest=tint.getText();
        String tloanpa=tlonpay.getText();
        String riskfund=risk.getText();
        String paymen=payment.getText();
        String nextinstall=nins.getText();
        String currentbal=bal.getText();
        Date dae=jDateChooser1.getDate();
        String commen=jTextArea1.getText();
        String typee=(String) jComboBox1.getSelectedItem();
        String totapay=totalpay.getText();
        
        connection connect=new connection();
        conn=connect.Connectdb();
        try{
        String sql="INSERT INTO `mini_statement`(`member_identification`, `minute_number`, `approved_loan`, `installments`, `first-perio`, "
                + "`total_interest`, `total_loan_pay`, `risk_fund`, `date_made_payment`, `loan_type`, `next_installment`, `current_balance`, "
                + "`comment`, `amount_paid`, `total_paid`) VALUES ('"+member+"','"+minite+"','"+aplo+"','"+insta+"','"+fast+"','"+totinterest+"'"
                + ",'"+tloanpa+"','"+riskfund+"','"+dae+"','"+typee+"','"+nextinstall+"','"+currentbal+"','"+commen+"','"+paymen+"','"+totapay+"')";
        pst=conn.prepareStatement(sql);
        pst.execute();
        
        
        }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            }

        try{
        String sql="UPDATE `mini_statement` SET `minute_number`='"+minite+"',`approved_loan`='"+aplo+"',"
                + "`installments`='"+insta+"',`first-perio`='"+fast+"',`total_interest`='"+totinterest+"',`total_loan_pay`='"+tloanpa+"',`risk_fund`='"+riskfund+"',"
                + "`date_made_payment`='"+dae+"',`loan_type`='"+typee+"',`next_installment`='"+nextinstall+"',`current_balance`='"+currentbal+"',"
                + "`comment`='"+commen+"',`amount_paid`='"+paymen+"',`total_paid`='"+totapay+"' WHERE `member_identification`='"+member+"'";
         pst=conn.prepareStatement(sql);
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Payment made successfully","LUYO",JOptionPane.INFORMATION_MESSAGE);
        }
       catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    if(jComboBox1.getSelectedItem().equals("Normal Loan")){
    String member=memberidentification.getText();
    String loan=(String)jComboBox1.getSelectedItem();
    connection connect=new connection();
    conn=connect.Connectdb();
    try{
    java.sql.Statement stm = conn.createStatement();
    String sql="SELECT * FROM `loan_repayment` WHERE member_identification='"+member+" && loan_type='"+loan+"";
    rs=stm.executeQuery(sql);
    
    if(rs.next()){
    String loannum=rs.getString("minute_number");
    String approved=rs.getString("approved_loan");
    String instal=rs.getString("installments");
    String fast=rs.getString("first_perio");
    String inte=rs.getString("total_interest");
    String loanp=rs.getString("total_loan_pay");
    String ris=rs.getString("risk_fund");
    
    minum.setText(loannum);
    aplon.setText(approved);
    inst.setText(instal);
    fpd.setText(fast);
    tint.setText(inte);
    tlonpay.setText(loanp);
    risk.setText(ris);
    
    }
    else{
      minum.setText("");
    aplon.setText("");
    inst.setText("");
    fpd.setText("");
    tint.setText("");
    tlonpay.setText("");
    risk.setText("");      
            
            }
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    }
    
     if(jComboBox1.getSelectedItem().equals("Special Loan")){
    String member=memberidentification.getText();
    String loan=(String)jComboBox1.getSelectedItem();
    connection connect=new connection();
    conn=connect.Connectdb();
    try{
    java.sql.Statement stm = conn.createStatement();
    String sql="SELECT * FROM `loan_repayment` WHERE member_identification='"+member+" && loan_type='"+loan+"";
    rs=stm.executeQuery(sql);
    
    if(rs.next()){
    String loannum=rs.getString("minute_number");
    String approved=rs.getString("approved_loan");
    String instal=rs.getString("installments");
    String fast=rs.getString("first_perio");
    String inte=rs.getString("total_interest");
    String loanp=rs.getString("total_loan_pay");
    String ris=rs.getString("risk_fund");
    
    minum.setText(loannum);
    aplon.setText(approved);
    inst.setText(instal);
    fpd.setText(fast);
    tint.setText(inte);
    tlonpay.setText(loanp);
    risk.setText(ris);
    
    }
    else{
      minum.setText("");
    aplon.setText("");
    inst.setText("");
    fpd.setText("");
    tint.setText("");
    tlonpay.setText("");
    risk.setText("");      
            
            }
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    }
     
    if(jComboBox1.getSelectedItem().equals("Emergency Loan")){
    String member=memberidentification.getText();
    String loan=(String)jComboBox1.getSelectedItem();
    connection connect=new connection();
    conn=connect.Connectdb();
    try{
    java.sql.Statement stm = conn.createStatement();
    String sql="SELECT * FROM `loan_repayment` WHERE member_identification='"+member+" && loan_type='"+loan+"";
    rs=stm.executeQuery(sql);
    
    if(rs.next()){
    String loannum=rs.getString("minute_number");
    String approved=rs.getString("approved_loan");
    String instal=rs.getString("installments");
    String fast=rs.getString("first_perio");
    String inte=rs.getString("total_interest");
    String loanp=rs.getString("total_loan_pay");
    String ris=rs.getString("risk_fund");
    
    minum.setText(loannum);
    aplon.setText(approved);
    inst.setText(instal);
    fpd.setText(fast);
    tint.setText(inte);
    tlonpay.setText(loanp);
    risk.setText(ris);
    
    }
    else{
      minum.setText("");
    aplon.setText("");
    inst.setText("");
    fpd.setText("");
    tint.setText("");
    tlonpay.setText("");
    risk.setText("");      
            
            }
    }
    catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
    
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    float in=Float.parseFloat(inst.getText());
    float pay=Float.parseFloat(payment.getText());
    float lopay=Float.parseFloat(tlonpay.getText());
    float bala=in-pay;
    float ball=in+bala;
    //float currentbal=lopay-pay;
    if(pay>=in){
    jTextArea1.setText("Validation successful");
    nins.setText(String.valueOf(in));
    }
    else{
    jTextArea1.setText("Amount below installment.\n ");
    nins.setText(String.valueOf(ball));
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void paymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentKeyReleased
     float amou=Float.parseFloat(amount.getText());
     float pay=Float.parseFloat(payment.getText());
     float paye=Float.parseFloat(tlonpay.getText());
     
     float tota=amou+pay;
     float total=paye-tota;
     bal.setText(String.valueOf(total));
     totalpay.setText(String.valueOf(tota));
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loan_repayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField aplon;
    private javax.swing.JTextField bal;
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator1;
    private com.toedter.calendar.demo.BirthdayEvaluator birthdayEvaluator2;
    private javax.swing.JTextField contact;
    private com.toedter.calendar.DateUtil dateUtil1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f11;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField fpd;
    private javax.swing.JTextField inst;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private org.freixas.jcalendar.JCalendar jCalendar2;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField maritalstatus;
    private javax.swing.JTextField memberidentification;
    private javax.swing.JTextField middlename;
    private javax.swing.JTextField minum;
    private javax.swing.JTextField national;
    private javax.swing.JTextField nins;
    private javax.swing.JTextField payment;
    private javax.swing.JTextField risk;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s7;
    private javax.swing.JLabel s8;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField tint;
    private javax.swing.JTextField tlonpay;
    private javax.swing.JTextField totalpay;
    // End of variables declaration//GEN-END:variables
}
